// ─── gerberGenerator.ts ── Real Gerber RS-274X / Excellon / BOM / PnP ───────
// Generates valid Gerber files that work in gerbv, Tracespace, etc.

import type {
  Point, BoardState, BrdTrace, BrdVia, BrdComponent, BrdPad, BrdZone,
} from '../types';

// ─── Coordinate formatting ──────────────────────────────────────────────────
// RS-274X format spec: FSLAX46Y46
// Leading zeros omitted, absolute coordinates.
// 4 integer digits, 6 decimal digits -> units in mm, 1 unit = 0.000001 mm

const COORD_MULTIPLIER = 1_000_000; // 10^6 for 4.6 format

function fmtCoord(mm: number): string {
  const v = Math.round(mm * COORD_MULTIPLIER);
  return v.toString();
}

function fmtXY(x: number, y: number): string {
  return `X${fmtCoord(x)}Y${fmtCoord(y)}`;
}

// ─── Aperture management ────────────────────────────────────────────────────

interface Aperture {
  code: number;    // D10, D11, ...
  type: 'C' | 'R' | 'O';  // Circle, Rectangle, Obround
  params: number[];  // [diameter] or [width, height]
}

class ApertureTable {
  private apertures: Aperture[] = [];
  private nextCode = 10;
  private cache = new Map<string, number>();

  getCircle(diameter: number): number {
    const key = `C:${diameter.toFixed(6)}`;
    const cached = this.cache.get(key);
    if (cached !== undefined) return cached;
    const code = this.nextCode++;
    this.apertures.push({ code, type: 'C', params: [diameter] });
    this.cache.set(key, code);
    return code;
  }

  getRect(w: number, h: number): number {
    const key = `R:${w.toFixed(6)}x${h.toFixed(6)}`;
    const cached = this.cache.get(key);
    if (cached !== undefined) return cached;
    const code = this.nextCode++;
    this.apertures.push({ code, type: 'R', params: [w, h] });
    this.cache.set(key, code);
    return code;
  }

  getObround(w: number, h: number): number {
    const key = `O:${w.toFixed(6)}x${h.toFixed(6)}`;
    const cached = this.cache.get(key);
    if (cached !== undefined) return cached;
    const code = this.nextCode++;
    this.apertures.push({ code, type: 'O', params: [w, h] });
    this.cache.set(key, code);
    return code;
  }

  toGerber(): string {
    const lines: string[] = [];
    for (const ap of this.apertures) {
      if (ap.type === 'C') {
        lines.push(`%ADD${ap.code}C,${ap.params[0].toFixed(6)}*%`);
      } else if (ap.type === 'R') {
        lines.push(`%ADD${ap.code}R,${ap.params[0].toFixed(6)}X${ap.params[1].toFixed(6)}*%`);
      } else if (ap.type === 'O') {
        lines.push(`%ADD${ap.code}O,${ap.params[0].toFixed(6)}X${ap.params[1].toFixed(6)}*%`);
      }
    }
    return lines.join('\n');
  }
}

// ─── Gerber header ──────────────────────────────────────────────────────────

function gerberHeader(layerName: string): string {
  const now = new Date();
  const dateStr = now.toISOString().replace(/[-:T]/g, '').slice(0, 14);
  return [
    'G04 Generated by RouteAI EDA*',
    `G04 Layer: ${layerName}*`,
    `G04 Date: ${dateStr}*`,
    '%MOMM*%',                          // Units: millimeters
    '%FSLAX46Y46*%',                    // Format: 4 integer, 6 decimal
    '%IPPOS*%',                         // Image polarity: positive
    '%LPD*%',                           // Layer polarity: dark
  ].join('\n');
}

function gerberFooter(): string {
  return 'M02*';
}

// ─── Resolve pad world coordinates ──────────────────────────────────────────

interface PadWorld {
  cx: number;
  cy: number;
  width: number;
  height: number;
  shape: string;
  drill: number;
  netId: string;
  layers: string[];
  compRef: string;
  padNum: string;
}

function resolvePads(board: BoardState): PadWorld[] {
  const result: PadWorld[] = [];
  for (const comp of board.components) {
    const rad = (comp.rotation * Math.PI) / 180;
    const cosR = Math.cos(rad);
    const sinR = Math.sin(rad);
    for (const pad of comp.pads) {
      const rx = pad.x * cosR - pad.y * sinR;
      const ry = pad.x * sinR + pad.y * cosR;
      // If rotated 90/270, swap width/height for non-circular pads
      const isSwapped = (comp.rotation === 90 || comp.rotation === 270) && pad.shape !== 'circle';
      result.push({
        cx: comp.x + rx,
        cy: comp.y + ry,
        width: isSwapped ? pad.height : pad.width,
        height: isSwapped ? pad.width : pad.height,
        shape: pad.shape,
        drill: pad.drill ?? 0,
        netId: pad.netId ?? '',
        layers: pad.layers,
        compRef: comp.ref,
        padNum: pad.number,
      });
    }
  }
  return result;
}

// ─── Generate copper layer Gerber ───────────────────────────────────────────

export function generateGerber(board: BoardState, layer: string): string {
  const lines: string[] = [];
  const apt = new ApertureTable();

  lines.push(gerberHeader(layer));

  // Pre-scan all needed apertures BEFORE emitting the aperture table.
  // This ensures every aperture is defined exactly once in the header.
  const pads = resolvePads(board);
  const layerTraces = board.traces.filter(t => t.layer === layer);
  const layerZones = board.zones.filter(z => z.layer === layer);

  // Traces need round apertures for each width
  const traceApertures = new Map<number, number>();
  for (const trace of layerTraces) {
    if (!traceApertures.has(trace.width)) {
      traceApertures.set(trace.width, apt.getCircle(trace.width));
    }
  }

  // Pads need various aperture shapes
  const padApertures = new Map<string, number>();
  for (const pad of pads) {
    if (!pad.layers.includes(layer)) continue;
    const key = `${pad.shape}:${pad.width}:${pad.height}`;
    if (!padApertures.has(key)) {
      switch (pad.shape) {
        case 'circle':
          padApertures.set(key, apt.getCircle(pad.width));
          break;
        case 'rect':
        case 'roundrect':
          padApertures.set(key, apt.getRect(pad.width, pad.height));
          break;
        case 'oval':
          padApertures.set(key, apt.getObround(pad.width, pad.height));
          break;
        default:
          padApertures.set(key, apt.getRect(pad.width, pad.height));
      }
    }
  }

  // Via apertures (on copper layers)
  const viaApertures = new Map<number, number>();
  if (layer.includes('Cu')) {
    for (const via of board.vias) {
      if (!via.layers.includes(layer)) continue;
      if (!viaApertures.has(via.size)) {
        viaApertures.set(via.size, apt.getCircle(via.size));
      }
    }
  }

  // Edge.Cuts outline aperture
  let outlineApCode: number | null = null;
  if (layer === 'Edge.Cuts') {
    const outline = board.outline.points;
    if (outline.length >= 2) {
      outlineApCode = apt.getCircle(0.05);
    }
  }

  // Silkscreen aperture
  let silkApCode: number | null = null;
  if (layer.includes('SilkS')) {
    silkApCode = apt.getCircle(0.15);
  }

  // Paste layer apertures - pre-scan (SMD pads only, slight contraction)
  const pasteContraction = 0.05; // 50um smaller than pad (paste pulls in)
  const pastePadApertures = new Map<string, number>();
  if (layer.includes('Paste')) {
    const targetCuLayer = layer.startsWith('F.') ? 'F.Cu' : 'B.Cu';
    for (const pad of pads) {
      if (!pad.layers.includes(targetCuLayer)) continue;
      // Only SMD pads (no drill hole) get paste
      if (pad.drill > 0) continue;
      const w = Math.max(0.01, pad.width - pasteContraction * 2);
      const h = Math.max(0.01, pad.height - pasteContraction * 2);
      const key = `${pad.shape}:${w.toFixed(6)}:${h.toFixed(6)}`;
      if (!pastePadApertures.has(key)) {
        if (pad.shape === 'circle') {
          pastePadApertures.set(key, apt.getCircle(w));
        } else if (pad.shape === 'oval') {
          pastePadApertures.set(key, apt.getObround(w, h));
        } else {
          pastePadApertures.set(key, apt.getRect(w, h));
        }
      }
    }
  }

  // Solder mask apertures - pre-scan all needed apertures
  const maskExpansion = 0.05; // 50um expansion
  const maskPadApertures = new Map<string, number>();
  const maskViaApertures = new Map<number, number>();
  if (layer.includes('Mask')) {
    const targetCuLayer = layer.startsWith('F.') ? 'F.Cu' : 'B.Cu';
    for (const pad of pads) {
      if (!pad.layers.includes(targetCuLayer)) continue;
      const w = pad.width + maskExpansion * 2;
      const h = pad.height + maskExpansion * 2;
      const key = `${pad.shape}:${w.toFixed(6)}:${h.toFixed(6)}`;
      if (!maskPadApertures.has(key)) {
        if (pad.shape === 'circle') {
          maskPadApertures.set(key, apt.getCircle(w));
        } else if (pad.shape === 'oval') {
          maskPadApertures.set(key, apt.getObround(w, h));
        } else {
          maskPadApertures.set(key, apt.getRect(w, h));
        }
      }
    }
    for (const via of board.vias) {
      const maskSize = via.size + maskExpansion * 2;
      if (!maskViaApertures.has(maskSize)) {
        maskViaApertures.set(maskSize, apt.getCircle(maskSize));
      }
    }
  }

  // ── Write all aperture definitions once ──────────────────────────────
  lines.push(apt.toGerber());

  // ── Draw traces ─────────────────────────────────────────────────────
  for (const trace of layerTraces) {
    if (trace.points.length < 2) continue;
    const apCode = traceApertures.get(trace.width) ?? 'D10';
    lines.push(`D${apCode}*`);
    // Move to start
    lines.push(`${fmtXY(trace.points[0].x, trace.points[0].y)}D02*`);
    // Draw to each subsequent point
    for (let i = 1; i < trace.points.length; i++) {
      lines.push(`${fmtXY(trace.points[i].x, trace.points[i].y)}D01*`);
    }
  }

  // ── Flash pads (skip paste layers — handled separately below) ──────
  if (!layer.includes('Paste')) {
    for (const pad of pads) {
      if (!pad.layers.includes(layer)) continue;
      const key = `${pad.shape}:${pad.width}:${pad.height}`;
      const apCode = padApertures.get(key) ?? 'D10';
      lines.push(`D${apCode}*`);
      lines.push(`${fmtXY(pad.cx, pad.cy)}D03*`);
    }
  }

  // ── Flash vias ──────────────────────────────────────────────────────
  if (layer.includes('Cu')) {
    for (const via of board.vias) {
      if (!via.layers.includes(layer)) continue;
      const apCode = viaApertures.get(via.size) ?? 'D10';
      lines.push(`D${apCode}*`);
      lines.push(`${fmtXY(via.x, via.y)}D03*`);
    }
  }

  // ── Region fill for zones ───────────────────────────────────────────
  for (const zone of layerZones) {
    if (zone.points.length < 3) continue;
    lines.push('G36*');  // Begin region
    lines.push(`${fmtXY(zone.points[0].x, zone.points[0].y)}D02*`);
    for (let i = 1; i < zone.points.length; i++) {
      lines.push(`${fmtXY(zone.points[i].x, zone.points[i].y)}D01*`);
    }
    // Close back to first point
    lines.push(`${fmtXY(zone.points[0].x, zone.points[0].y)}D01*`);
    lines.push('G37*');  // End region
  }

  // ── Board outline for Edge.Cuts ─────────────────────────────────────
  if (layer === 'Edge.Cuts' && outlineApCode !== null) {
    const outline = board.outline.points;
    if (outline.length >= 2) {
      lines.push(`D${outlineApCode}*`);
      lines.push(`${fmtXY(outline[0].x, outline[0].y)}D02*`);
      for (let i = 1; i < outline.length; i++) {
        lines.push(`${fmtXY(outline[i].x, outline[i].y)}D01*`);
      }
      lines.push(`${fmtXY(outline[0].x, outline[0].y)}D01*`);
    }
  }

  // ── Silkscreen layers ───────────────────────────────────────────────
  if (layer.includes('SilkS') && silkApCode !== null) {
    const targetCuLayer = layer.startsWith('F.') ? 'F.Cu' : 'B.Cu';
    lines.push(`D${silkApCode}*`);
    for (const comp of board.components) {
      if (comp.layer !== targetCuLayer) continue;
      // Draw a small cross at the component origin as reference indicator
      const sz = 1.0;
      lines.push(`${fmtXY(comp.x - sz, comp.y)}D02*`);
      lines.push(`${fmtXY(comp.x + sz, comp.y)}D01*`);
      lines.push(`${fmtXY(comp.x, comp.y - sz)}D02*`);
      lines.push(`${fmtXY(comp.x, comp.y + sz)}D01*`);
    }
  }

  // ── Solder mask layers (inverted: openings for pads) ────────────────
  if (layer.includes('Mask')) {
    const targetCuLayer = layer.startsWith('F.') ? 'F.Cu' : 'B.Cu';
    for (const pad of pads) {
      if (!pad.layers.includes(targetCuLayer)) continue;
      const w = pad.width + maskExpansion * 2;
      const h = pad.height + maskExpansion * 2;
      const key = `${pad.shape}:${w.toFixed(6)}:${h.toFixed(6)}`;
      const apCode = maskPadApertures.get(key) ?? 'D10';
      lines.push(`D${apCode}*`);
      lines.push(`${fmtXY(pad.cx, pad.cy)}D03*`);
    }
    // Via mask openings
    for (const via of board.vias) {
      const maskSize = via.size + maskExpansion * 2;
      const apCode = maskViaApertures.get(maskSize) ?? 'D10';
      lines.push(`D${apCode}*`);
      lines.push(`${fmtXY(via.x, via.y)}D03*`);
    }
  }

  // ── Paste layers (SMD pads only, no through-hole, slight contraction) ──
  if (layer.includes('Paste')) {
    const targetCuLayer = layer.startsWith('F.') ? 'F.Cu' : 'B.Cu';
    for (const pad of pads) {
      if (!pad.layers.includes(targetCuLayer)) continue;
      // Only SMD pads — through-hole pads must not appear on paste layers
      if (pad.drill > 0) continue;
      const w = Math.max(0.01, pad.width - pasteContraction * 2);
      const h = Math.max(0.01, pad.height - pasteContraction * 2);
      const key = `${pad.shape}:${w.toFixed(6)}:${h.toFixed(6)}`;
      const apCode = pastePadApertures.get(key) ?? 'D10';
      lines.push(`D${apCode}*`);
      lines.push(`${fmtXY(pad.cx, pad.cy)}D03*`);
    }
    // Note: no via openings on paste layers (vias don't get solder paste)
  }

  lines.push(gerberFooter());
  return lines.join('\n');
}

// ─── Excellon drill file ────────────────────────────────────────────────────

interface DrillHit { x: number; y: number; diameter: number; }

/** Generate a single Excellon drill file from a list of drill hits */
function generateExcellonFromHits(hits: DrillHit[], comment: string): string {
  const lines: string[] = [];

  if (hits.length === 0) {
    return `; ${comment}\n; No drill hits\nM30\n`;
  }

  // Group by tool (diameter)
  const toolMap = new Map<number, DrillHit[]>();
  for (const hit of hits) {
    const d = Math.round(hit.diameter * 1000) / 1000; // round to 1um
    let arr = toolMap.get(d);
    if (!arr) { arr = []; toolMap.set(d, arr); }
    arr.push(hit);
  }

  // Sort tools by diameter
  const tools = Array.from(toolMap.entries()).sort((a, b) => a[0] - b[0]);

  // Header
  lines.push('M48');           // Begin header
  lines.push('; Generated by RouteAI EDA');
  lines.push(`; ${comment}`);
  lines.push('FMAT,2');        // Format 2
  lines.push('METRIC');        // Metric units

  // Tool table
  tools.forEach(([diameter], idx) => {
    const toolNum = idx + 1;
    lines.push(`T${toolNum}C${diameter.toFixed(3)}`);
  });

  lines.push('%');             // End header

  // Drill hits per tool
  tools.forEach(([diameter, drillHits], idx) => {
    const toolNum = idx + 1;
    lines.push(`T${toolNum}`);
    for (const hit of drillHits) {
      const xInt = Math.round(hit.x * 1000);
      const yInt = Math.round(hit.y * 1000);
      lines.push(`X${xInt}Y${yInt}`);
    }
  });

  lines.push('T0');
  lines.push('M30');          // End of program

  return lines.join('\n');
}

/** Generate the main through-hole drill file (PTH pads + through vias) */
export function generateDrill(board: BoardState): string {
  const hits: DrillHit[] = [];

  // Through vias only (or vias without viaType for backward compatibility)
  for (const via of board.vias) {
    const vType = via.viaType || 'through';
    if (vType === 'through') {
      hits.push({ x: via.x, y: via.y, diameter: via.drill });
    }
  }

  // PTH pads
  const pads = resolvePads(board);
  for (const pad of pads) {
    if (pad.drill > 0) {
      hits.push({ x: pad.cx, y: pad.cy, diameter: pad.drill });
    }
  }

  return generateExcellonFromHits(hits, 'Drill file - Through holes - Excellon format');
}

/** Group blind/buried/micro vias by layer pair and generate separate drill files */
export interface LayerPairDrillFile {
  fileName: string;
  content: string;
  viaType: string;
  startLayer: string;
  endLayer: string;
}

export function generateBlindBuriedDrills(board: BoardState): LayerPairDrillFile[] {
  const files: LayerPairDrillFile[] = [];

  // Group non-through vias by (viaType, startLayer, endLayer)
  const groups = new Map<string, { hits: DrillHit[]; viaType: string; startLayer: string; endLayer: string }>();

  for (const via of board.vias) {
    const vType = via.viaType || 'through';
    if (vType === 'through') continue; // handled by main drill file

    const startLayer = via.startLayer || via.layers[0] || 'F.Cu';
    const endLayer = via.endLayer || via.layers[via.layers.length - 1] || 'B.Cu';
    const key = `${vType}:${startLayer}:${endLayer}`;

    let group = groups.get(key);
    if (!group) {
      group = { hits: [], viaType: vType, startLayer, endLayer };
      groups.set(key, group);
    }
    group.hits.push({ x: via.x, y: via.y, diameter: via.drill });
  }

  for (const [, group] of groups) {
    const sLayer = group.startLayer.replace('.', '_');
    const eLayer = group.endLayer.replace('.', '_');
    const prefix = group.viaType === 'micro' ? 'micro' : group.viaType;
    const fileName = `drill_${prefix}_${sLayer}-${eLayer}.drl`;
    const comment = `${group.viaType} via drill file - ${group.startLayer} to ${group.endLayer} - Excellon format`;
    const content = generateExcellonFromHits(group.hits, comment);
    files.push({
      fileName,
      content,
      viaType: group.viaType,
      startLayer: group.startLayer,
      endLayer: group.endLayer,
    });
  }

  return files;
}

// ─── BOM CSV ────────────────────────────────────────────────────────────────

export function generateBOM(board: BoardState): string {
  const lines: string[] = [];
  lines.push('"Reference","Value","Footprint","Quantity"');

  // Group by value+footprint
  const groups = new Map<string, { refs: string[]; value: string; footprint: string }>();
  for (const comp of board.components) {
    const key = `${comp.value}|${comp.footprint}`;
    let g = groups.get(key);
    if (!g) {
      g = { refs: [], value: comp.value, footprint: comp.footprint };
      groups.set(key, g);
    }
    g.refs.push(comp.ref);
  }

  for (const g of groups.values()) {
    const refs = g.refs.sort().join(', ');
    lines.push(`"${refs}","${g.value}","${g.footprint}","${g.refs.length}"`);
  }

  return lines.join('\n');
}

// ─── Pick and Place CSV ─────────────────────────────────────────────────────

export function generatePickAndPlace(board: BoardState): string {
  const lines: string[] = [];
  lines.push('"Ref","Val","Package","PosX","PosY","Rot","Side"');

  for (const comp of board.components) {
    const side = comp.layer === 'F.Cu' ? 'top' : 'bottom';
    lines.push(
      `"${comp.ref}","${comp.value}","${comp.footprint}",` +
      `"${comp.x.toFixed(4)}","${comp.y.toFixed(4)}",` +
      `"${comp.rotation.toFixed(1)}","${side}"`
    );
  }

  return lines.join('\n');
}

// ─── Layer file name mapping ────────────────────────────────────────────────

const LAYER_FILE_NAMES: Record<string, string> = {
  'F.Cu': 'F_Cu.gbr',
  'B.Cu': 'B_Cu.gbr',
  'In1.Cu': 'In1_Cu.gbr',
  'In2.Cu': 'In2_Cu.gbr',
  'F.Mask': 'F_Mask.gbr',
  'B.Mask': 'B_Mask.gbr',
  'F.SilkS': 'F_SilkS.gbr',
  'B.SilkS': 'B_SilkS.gbr',
  'F.Paste': 'F_Paste.gbr',
  'B.Paste': 'B_Paste.gbr',
  'Edge.Cuts': 'Edge_Cuts.gbr',
};

// ─── Export all files ───────────────────────────────────────────────────────

export interface ExportFile {
  name: string;
  content: string;
  size: number;
}

export function generateAllFiles(
  board: BoardState,
  selectedLayers: string[] = ['F.Cu', 'B.Cu', 'F.SilkS', 'B.SilkS', 'F.Mask', 'B.Mask', 'Edge.Cuts']
): ExportFile[] {
  const files: ExportFile[] = [];

  // Gerber layers
  for (const layer of selectedLayers) {
    const content = generateGerber(board, layer);
    const fileName = LAYER_FILE_NAMES[layer] || `${layer.replace('.', '_')}.gbr`;
    files.push({
      name: fileName,
      content,
      size: content.length,
    });
  }

  // Main drill file (through-hole vias + PTH pads)
  const drill = generateDrill(board);
  files.push({ name: 'drill.drl', content: drill, size: drill.length });

  // Separate drill files for blind/buried/micro vias (required by fabs)
  const bbDrills = generateBlindBuriedDrills(board);
  for (const bbFile of bbDrills) {
    files.push({ name: bbFile.fileName, content: bbFile.content, size: bbFile.content.length });
  }

  // BOM
  const bom = generateBOM(board);
  files.push({ name: 'BOM.csv', content: bom, size: bom.length });

  // Pick and Place
  const pnp = generatePickAndPlace(board);
  files.push({ name: 'PickAndPlace.csv', content: pnp, size: pnp.length });

  return files;
}

// ─── ZIP export using manual ZIP construction ───────────────────────────────
// Minimal ZIP file generator (no external dependencies).
// Produces valid ZIP files with STORE (no compression) method.

function crc32(data: Uint8Array): number {
  let crc = 0xFFFFFFFF;
  for (let i = 0; i < data.length; i++) {
    crc ^= data[i];
    for (let j = 0; j < 8; j++) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xEDB88320 : 0);
    }
  }
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

function textToBytes(text: string): Uint8Array {
  return new TextEncoder().encode(text);
}

function writeLEU16(buf: Uint8Array, offset: number, value: number) {
  buf[offset] = value & 0xFF;
  buf[offset + 1] = (value >> 8) & 0xFF;
}

function writeLEU32(buf: Uint8Array, offset: number, value: number) {
  buf[offset] = value & 0xFF;
  buf[offset + 1] = (value >> 8) & 0xFF;
  buf[offset + 2] = (value >> 16) & 0xFF;
  buf[offset + 3] = (value >> 24) & 0xFF;
}

export function exportAll(board: BoardState, selectedLayers?: string[]): Blob {
  const files = generateAllFiles(board, selectedLayers);

  // Build ZIP file
  const localHeaders: Uint8Array[] = [];
  const centralEntries: Uint8Array[] = [];
  let offset = 0;

  const now = new Date();
  const dosTime = ((now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1)) & 0xFFFF;
  const dosDate = (((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate()) & 0xFFFF;

  for (const file of files) {
    const nameBytes = textToBytes(file.name);
    const dataBytes = textToBytes(file.content);
    const crc = crc32(dataBytes);

    // Local file header (30 bytes + name + data)
    const localHeader = new Uint8Array(30 + nameBytes.length + dataBytes.length);
    writeLEU32(localHeader, 0, 0x04034B50);  // Local file header signature
    writeLEU16(localHeader, 4, 20);           // Version needed (2.0)
    writeLEU16(localHeader, 6, 0);            // General purpose bit flag
    writeLEU16(localHeader, 8, 0);            // Compression: STORE
    writeLEU16(localHeader, 10, dosTime);     // Last mod time
    writeLEU16(localHeader, 12, dosDate);     // Last mod date
    writeLEU32(localHeader, 14, crc);         // CRC-32
    writeLEU32(localHeader, 18, dataBytes.length);  // Compressed size
    writeLEU32(localHeader, 22, dataBytes.length);  // Uncompressed size
    writeLEU16(localHeader, 26, nameBytes.length);  // File name length
    writeLEU16(localHeader, 28, 0);           // Extra field length

    localHeader.set(nameBytes, 30);
    localHeader.set(dataBytes, 30 + nameBytes.length);
    localHeaders.push(localHeader);

    // Central directory entry (46 bytes + name)
    const centralEntry = new Uint8Array(46 + nameBytes.length);
    writeLEU32(centralEntry, 0, 0x02014B50);  // Central directory signature
    writeLEU16(centralEntry, 4, 20);           // Version made by
    writeLEU16(centralEntry, 6, 20);           // Version needed
    writeLEU16(centralEntry, 8, 0);            // Flags
    writeLEU16(centralEntry, 10, 0);           // Compression: STORE
    writeLEU16(centralEntry, 12, dosTime);
    writeLEU16(centralEntry, 14, dosDate);
    writeLEU32(centralEntry, 16, crc);
    writeLEU32(centralEntry, 20, dataBytes.length);
    writeLEU32(centralEntry, 24, dataBytes.length);
    writeLEU16(centralEntry, 28, nameBytes.length);
    writeLEU16(centralEntry, 30, 0);           // Extra field length
    writeLEU16(centralEntry, 32, 0);           // Comment length
    writeLEU16(centralEntry, 34, 0);           // Disk number start
    writeLEU16(centralEntry, 36, 0);           // Internal file attributes
    writeLEU32(centralEntry, 38, 0);           // External file attributes
    writeLEU32(centralEntry, 42, offset);      // Relative offset of local header

    centralEntry.set(nameBytes, 46);
    centralEntries.push(centralEntry);

    offset += localHeader.length;
  }

  // End of central directory record (22 bytes)
  const centralDirOffset = offset;
  let centralDirSize = 0;
  for (const entry of centralEntries) centralDirSize += entry.length;

  const endOfCentral = new Uint8Array(22);
  writeLEU32(endOfCentral, 0, 0x06054B50);               // End of central dir signature
  writeLEU16(endOfCentral, 4, 0);                         // Disk number
  writeLEU16(endOfCentral, 6, 0);                         // Disk with central dir
  writeLEU16(endOfCentral, 8, files.length);              // Entries on this disk
  writeLEU16(endOfCentral, 10, files.length);             // Total entries
  writeLEU32(endOfCentral, 12, centralDirSize);           // Central dir size
  writeLEU32(endOfCentral, 16, centralDirOffset);         // Offset of central dir
  writeLEU16(endOfCentral, 20, 0);                        // Comment length

  // Concatenate all parts
  const totalSize = offset + centralDirSize + 22;
  const zipBuffer = new Uint8Array(totalSize);
  let pos = 0;
  for (const lh of localHeaders) {
    zipBuffer.set(lh, pos);
    pos += lh.length;
  }
  for (const ce of centralEntries) {
    zipBuffer.set(ce, pos);
    pos += ce.length;
  }
  zipBuffer.set(endOfCentral, pos);

  return new Blob([zipBuffer], { type: 'application/zip' });
}
