"""Routing style profile — statistical feature vector extracted from a PCB board.

This is a pure data class with no LLM dependency. It captures the routing
style of an existing board so it can be reused as a reference for new designs.
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass, field


@dataclass
class RoutingStyleProfile:
    """Statistical routing style profile extracted from a PCB board.

    Every field is computed deterministically from board geometry — no LLM
    needed.  The optional ``summary`` field can be populated by an LLM for
    human-readable interpretation.
    """

    board_name: str = ""
    net_count: int = 0
    trace_count: int = 0
    via_count: int = 0

    # Track geometry
    trace_width_histogram: dict[float, int] = field(default_factory=dict)
    trace_width_by_net_class: dict[str, float] = field(default_factory=dict)
    avg_segment_length_mm: float = 0.0

    # Via patterns
    via_density_per_cm2: float = 0.0
    via_types_ratio: dict[str, float] = field(default_factory=dict)  # through/blind/buried/micro
    avg_vias_per_net: float = 0.0

    # Routing preferences
    preferred_angles: list[int] = field(default_factory=list)  # [0, 45, 90] or [0, 90]
    manhattan_ratio: float = 0.0  # actual_length / manhattan_distance (1.0 = pure manhattan)

    # Layer usage
    layer_utilization: dict[str, float] = field(default_factory=dict)  # layer -> usage fraction
    avg_layer_transitions_per_net: float = 0.0

    # Spacing
    avg_clearance_mm: float = 0.0
    min_clearance_mm: float = 0.0
    diff_pair_gap_ratio: float = 0.0  # gap/width for diff pairs

    # Board info
    board_area_mm2: float = 0.0
    layer_count: int = 0

    # Semantic summary (optionally generated by LLM, ~500 tokens)
    summary: str = ""

    def to_dict(self) -> dict:
        """Serialize to a plain dict for storage / JSON export."""
        return dataclasses.asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> RoutingStyleProfile:
        """Reconstruct a profile from a serialized dict."""
        known = {f.name for f in dataclasses.fields(cls)}
        return cls(**{k: v for k, v in data.items() if k in known})
