"""Compliance report generator.

Produces HTML and PDF reports from IPC compliance check results.
Includes executive summary, detailed per-standard results, and
pass/fail visualizations.
"""

from __future__ import annotations

import os
import time
from typing import Optional

from routeai_solver.compliance.ipc_checker import (
    CheckResult,
    ComplianceCheck,
    ComplianceReport,
)


# ---------------------------------------------------------------------------
# HTML Templates
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>IPC Compliance Report</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #f5f5f5; color: #333; line-height: 1.6;
  }}
  .container {{ max-width: 900px; margin: 0 auto; padding: 20px; }}
  .header {{
    background: #1a1a2e; color: #fff; padding: 30px;
    border-radius: 8px 8px 0 0; margin-bottom: 0;
  }}
  .header h1 {{ font-size: 24px; margin-bottom: 8px; }}
  .header .meta {{ font-size: 13px; color: #aaa; }}
  .executive-summary {{
    background: #fff; padding: 24px; border: 1px solid #e0e0e0;
    border-top: none; margin-bottom: 20px;
  }}
  .summary-grid {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 16px; margin: 16px 0;
  }}
  .stat-card {{
    background: #f8f9fa; border-radius: 8px; padding: 16px;
    text-align: center; border: 1px solid #e9ecef;
  }}
  .stat-card .number {{ font-size: 28px; font-weight: 700; }}
  .stat-card .label {{ font-size: 12px; color: #666; text-transform: uppercase; }}
  .pass {{ color: #28a745; }}
  .fail {{ color: #dc3545; }}
  .warning {{ color: #ffc107; }}
  .na {{ color: #6c757d; }}
  .overall-pass {{
    display: inline-block; padding: 6px 16px; border-radius: 20px;
    font-weight: 700; font-size: 14px; text-transform: uppercase;
  }}
  .overall-pass.pass-bg {{ background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }}
  .overall-pass.fail-bg {{ background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }}
  .standard-section {{
    background: #fff; border: 1px solid #e0e0e0; border-radius: 8px;
    margin-bottom: 20px; overflow: hidden;
  }}
  .standard-header {{
    background: #f8f9fa; padding: 16px 20px;
    border-bottom: 1px solid #e0e0e0;
    display: flex; justify-content: space-between; align-items: center;
  }}
  .standard-header h2 {{ font-size: 18px; }}
  table {{
    width: 100%; border-collapse: collapse; font-size: 13px;
  }}
  th {{
    background: #f1f3f5; padding: 10px 12px; text-align: left;
    font-weight: 600; border-bottom: 2px solid #dee2e6;
  }}
  td {{
    padding: 10px 12px; border-bottom: 1px solid #eee;
    vertical-align: top;
  }}
  tr:hover {{ background: #f8f9fa; }}
  .badge {{
    display: inline-block; padding: 2px 10px; border-radius: 12px;
    font-size: 11px; font-weight: 600; text-transform: uppercase;
  }}
  .badge-pass {{ background: #d4edda; color: #155724; }}
  .badge-fail {{ background: #f8d7da; color: #721c24; }}
  .badge-warning {{ background: #fff3cd; color: #856404; }}
  .badge-na {{ background: #e9ecef; color: #495057; }}
  .footer {{
    text-align: center; padding: 20px; font-size: 12px; color: #999;
  }}
  .details {{ font-size: 12px; color: #666; margin-top: 4px; }}
  @media print {{
    body {{ background: #fff; }}
    .container {{ max-width: 100%; }}
    .standard-section {{ break-inside: avoid; }}
  }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>IPC Compliance Report</h1>
    <div class="meta">
      Generated by RouteAI EDA &middot; {date}
    </div>
  </div>

  <div class="executive-summary">
    <h2 style="margin-bottom: 12px;">Executive Summary</h2>
    <div>
      Overall Result:
      <span class="overall-pass {overall_class}">{overall_result}</span>
    </div>
    <div class="summary-grid">
      <div class="stat-card">
        <div class="number">{total_standards}</div>
        <div class="label">Standards Checked</div>
      </div>
      <div class="stat-card">
        <div class="number pass">{total_pass}</div>
        <div class="label">Checks Passed</div>
      </div>
      <div class="stat-card">
        <div class="number fail">{total_fail}</div>
        <div class="label">Checks Failed</div>
      </div>
      <div class="stat-card">
        <div class="number warning">{total_warnings}</div>
        <div class="label">Warnings</div>
      </div>
    </div>
  </div>

  {standard_sections}

  <div class="footer">
    RouteAI EDA Compliance Report &middot; Generated {date}
    <br>This report is for design review purposes. Final compliance determination
    requires physical testing per the referenced IPC standards.
  </div>
</div>
</body>
</html>
"""

_STANDARD_SECTION_TEMPLATE = """\
  <div class="standard-section">
    <div class="standard-header">
      <h2>{standard} (Class {class_level})</h2>
      <span class="overall-pass {pass_class}">{pass_text}</span>
    </div>
    <table>
      <thead>
        <tr>
          <th style="width:15%;">Clause</th>
          <th style="width:30%;">Description</th>
          <th style="width:10%;">Result</th>
          <th style="width:18%;">Measured</th>
          <th style="width:18%;">Required</th>
        </tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
    <div style="padding: 12px 20px; font-size: 13px; color: #666; border-top: 1px solid #eee;">
      {summary}
    </div>
  </div>
"""

_ROW_TEMPLATE = """\
        <tr>
          <td><strong>{clause_ref}</strong></td>
          <td>
            {description}
            {details_html}
          </td>
          <td><span class="badge {badge_class}">{result}</span></td>
          <td>{measured}</td>
          <td>{required}</td>
        </tr>
"""


# ---------------------------------------------------------------------------
# Compliance Report Generator
# ---------------------------------------------------------------------------

class ComplianceReportGenerator:
    """Generates formatted compliance reports from check results.

    Produces HTML reports directly and PDF reports via HTML-to-PDF
    conversion (requires an external tool like weasyprint or wkhtmltopdf,
    falls back to writing raw HTML if unavailable).
    """

    @staticmethod
    def _result_badge_class(result: CheckResult) -> str:
        return {
            CheckResult.PASS: "badge-pass",
            CheckResult.FAIL: "badge-fail",
            CheckResult.WARNING: "badge-warning",
            CheckResult.NOT_APPLICABLE: "badge-na",
        }.get(result, "badge-na")

    @staticmethod
    def _result_label(result: CheckResult) -> str:
        return {
            CheckResult.PASS: "PASS",
            CheckResult.FAIL: "FAIL",
            CheckResult.WARNING: "WARN",
            CheckResult.NOT_APPLICABLE: "N/A",
        }.get(result, "N/A")

    def generate_html(
        self, reports: list[ComplianceReport]
    ) -> str:
        """Generate an HTML compliance report.

        Args:
            reports: List of ComplianceReport objects from IPC checks.

        Returns:
            Complete HTML string.
        """
        date_str = time.strftime("%Y-%m-%d %H:%M:%S")

        # Aggregate stats
        total_pass = sum(r.pass_count for r in reports)
        total_fail = sum(r.fail_count for r in reports)
        total_warnings = sum(r.warning_count for r in reports)
        overall_passed = all(r.passed for r in reports)

        # Build standard sections
        sections_html: list[str] = []

        for report in reports:
            rows_html: list[str] = []
            for check in report.checks:
                details_html = ""
                if check.details:
                    details_html = f'<div class="details">{_escape_html(check.details)}</div>'

                rows_html.append(_ROW_TEMPLATE.format(
                    clause_ref=_escape_html(check.clause_ref),
                    description=_escape_html(check.description),
                    details_html=details_html,
                    badge_class=self._result_badge_class(check.result),
                    result=self._result_label(check.result),
                    measured=_escape_html(check.measured_value or "-"),
                    required=_escape_html(check.required_value or "-"),
                ))

            sections_html.append(_STANDARD_SECTION_TEMPLATE.format(
                standard=_escape_html(report.standard),
                class_level=report.class_level,
                pass_class="pass-bg" if report.passed else "fail-bg",
                pass_text="PASS" if report.passed else "FAIL",
                rows="\n".join(rows_html),
                summary=_escape_html(report.summary),
            ))

        html = _HTML_TEMPLATE.format(
            date=date_str,
            overall_result="PASS" if overall_passed else "FAIL",
            overall_class="pass-bg" if overall_passed else "fail-bg",
            total_standards=len(reports),
            total_pass=total_pass,
            total_fail=total_fail,
            total_warnings=total_warnings,
            standard_sections="\n".join(sections_html),
        )

        return html

    def generate_pdf(
        self,
        reports: list[ComplianceReport],
        output_path: str,
    ) -> str:
        """Generate a PDF compliance report.

        Tries to use weasyprint for HTML-to-PDF conversion. Falls back
        to writing an HTML file if weasyprint is not available.

        Args:
            reports: List of ComplianceReport objects.
            output_path: Path for the output PDF file.

        Returns:
            Actual file path written (may be .html if PDF generation
            was not available).
        """
        html_content = self.generate_html(reports)
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

        # Attempt PDF generation with weasyprint
        try:
            from weasyprint import HTML as WeasyprintHTML
            WeasyprintHTML(string=html_content).write_pdf(output_path)
            return output_path
        except ImportError:
            pass

        # Attempt with xhtml2pdf (pisa)
        try:
            from xhtml2pdf import pisa
            with open(output_path, "wb") as f:
                result = pisa.CreatePDF(html_content, dest=f)
                if not result.err:
                    return output_path
        except ImportError:
            pass

        # Fallback: write HTML file
        html_path = output_path.rsplit(".", 1)[0] + ".html"
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        return html_path


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
